bcmdhd: add missing ) for call to DHD_ERROR
bcmdhd4389/dhd_log_dump.c:1575:2: error: unterminated function-like macro invocation
   DHD_ERROR(("%s: logdump_prsrv_tailsize = %uKB \n",
   ^

Signed-off-by: Pat Tjin <pattjin@google.com>
Change-Id: Ia96f4298d42ecd3852099a116879481986980493